version: "3.3"

services:
  kong:
    image: mvp-k8s/kong:1.0
    build:
      context: .
      dockerfile: kong/Dockerfile
    hostname: kong
  connect:
    image:
      mvp-k8s/connect:1.0
    build:
      context: .
      dockerfile: debezium/connect/Dockerfile