
#Create admin consumer
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: admin
  annotations:
    kubernetes.io/ingress.class: kong
username: admin

---
# Create user consumer
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user
  annotations:
    kubernetes.io/ingress.class: kong
username: user
